apiVersion: apps/v1
kind: Deployment
metadata:
  name: wizard-server-deployment
  labels:
    app: wizard-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wizard-server
  template:
    metadata:
      labels:
        app: wizard-server
    spec:
      containers:
      - name: wizard-server
        image: wizard-server
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: WIZARD_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: wizard-db-secret
              key: root-username
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wizard-db-secret
              key: root-password
        - name: WIZARD_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: wizard-db-config
              key: wizard-db-name

---

apiVersion: v1
kind: Service
metadata:
  name: wizard-server-service
spec:
  type: NodePort
  selector:
    app: wizard-server
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 80
    nodePort: 30101
